/* eslint-disable import/no-anonymous-default-export */
import { LOCALES } from "../locales";

export default {
    [LOCALES.FINNISH]: {
        // common
        auth_button: "Kirjaudu sisään Googlella",
        auth_button_short: "Kirjaudu sisään",
        skills: "taidot",
        careers: "Urat",
        month: "kk",
        terms: "Ehdot",
        policy: "Tietosuojakäytäntö",
        policy_content: "Sisältöpolitiikka",

        //footer
        footer_skill_map: "Taitokartta",
        footer_career_explorer: "Uraopas",
        footer_courses: "Projektipohjaiset verkkokurssit",
        footer_pricing: "Hinnoittelu",

        //btns
        more: "lisää",
        share: "jaa",
        junior: "Helppo",
        middle: "Keskivaikea",
        senior: "Vaikea",

        // header
        header_profile: "Erikoistuminen:",
        nav_tutorials: "ura",
        nav_skills: "taidot",
        nav_premium: "oma suunnitelma",
        nav_upgrade: "päivitä",
        nav_ask: "kurssit",
        nav_exit: "Kirjaudu ulos",
        nav_workspace: "opeta",
        program_tutorial: "Valitse suosikkiaineesi:",
        edit_user_label: "Oma profiili",
        user_name_label: "Käyttäjänimi",
        user_picture_label: "Käyttäjän avatar",

        //profile
        profile_moto: "AI-käyttöiset videokurssit henkilökohtaisiin uratavoitteisiisi.",
        profile_description:
            "Opi tarvitsemasi asiat minuuteissa 24/7. Löydä parhaiten sopiva ura. Luo henkilökohtaisia kursseja videoineen, tietovisoineen ja AI-palautteineen uusien taitojen oppimiseksi.",
        profile_reccomended: "Suositellut urat",
        profile_learn: "Opiskele uusia asioita, saa ",
        profile_map: "kartta taidoistasi",
        profile_list_suggested: "ja ehdotettujen ",
        profile_upgrade_skills:
            "erikoistuminen on tietoalue, johon keskityt eniten. Olet oppinut",
        profile_specialisation_times: "kertaa",
        profile_specialisation_my: "Oma erikoistumiseni",
        profile_your_learned: " olet oppinut",
        profile_matching: " taitojasi vastaavat",
        add_explainer_short: "Liitä oppitunti tähän kurssiin",

        //skills
        skills_update_interest: "Päivitä YouTube-taitosi",
        skills_test_interest: "Etsi taitoja YouTubesta",

        //event
        event_create: "Luo kurssi alusta",
        event_finish: "Poistui live-huoneesta",
        event_proceed: "Live-huone",
        event_change: "Muokkaa ja myy kurssi",
        event_upgrade: "Aloita ilmainen kokeilu muokkaamiseen",
        event_btn_friend: "Jaa opiskelijoille",
        event_tasks_description: "Opit",
        event_result: "Tulos: luot",
        event_need: "Tarvitset",
        event_how: "Kuinka se toimii",

        create_event_title_edit: "Muokkaa ja myy kurssi",
        create_event_title_create: "Luo kurssi",
        create_event_remove_event: "Poista kurssi ikuisesti",
        create_event_title_label: "Kurssin otsikko",
        create_event_title_message: "Kurssilla on oltava otsikko",
        create_event_subject_label: "Valitse kurssin tagit haun ja järjestämisen helpottamiseksi",
        create_event_subject_extra:
            "Lähetä löytämätön tagi chatissa, lisäämme sen 15 minuutissa",
        create_event_subject_message:
            "Tapahtumaa ilman tageja ei luoda",
        create_event_cost_label: "Hinta opiskelijalle (min 2 $) / Saat, palvelun komissio",
        create_event_save: "Tallenna kurssi ja poistu",

        // event set date
        event_set_date_every_week: "Joka {päivä} klo {aika}",
        event_set_date_exist: "Tapahtuma on jo olemassa",
        event_set_date_added: "Tapahtuma lisätty",
        event_set_date_title: "Aikataulu",
        event_set_date_description: 'Kurssi ilman päivämäärää ja aikaa lisätään "Ilmoitukset"-osioon. Tämä vaihtoehto sopii ryhmän kokoamiseen.', event_set_date_schedule: "alkaen {päivämäärä} joka {päivä}, {aika}",
        event_set_date_remove_item: "Poista oppitunti",
        event_set_date_add_date: "Lisää päivämäärä ja aika",
        event_set_date_date: "Päivämäärä",
        event_set_date_time: "Aika",
        event_set_date_dont_repeat: "Älä toista",
        event_set_date_repeat: "Toista joka viikko",
        //groups
        group_groups: "Kouluttajan hallintapaneeli:",
        group_tutorial: "Luo kurssisi:",
        group_soon: "Ilmaiset esittelykurssit ↓",
        group_soon_description:
            "Mielenkiintoisimmat kurssit, jotka käyttäjämme loivat. Voit opiskella niitä ilmaiseksi.",

        // Participants list
        participants_list_subsicribe: "Tilaus",

        //Payment page
        premium: "Premium",
        premium_pro: "Pro",
        premium_your: "Suunnitelmasi",
        premium_description:
            "Testaa kiinnostuksesi ja kehitä puuttuvia taitojasi",
        premium_pro_description:
            "Luo koulusi ja myy kursseja",
        premium_moneyback: "3 päivän ilmainen kokeilu",
        payment_premium_monthly: "Aloita ilmainen kokeilu",
        payment_title_creator: "Luojan suunnitelman ilmainen kokeilu",
        payment_title_premium: "Premium-suunnitelman ilmainen kokeilu",
        payment_title: "Valitse suunnitelmasi",
        payment_button: "Aloita ilmainen kokeilu",
        payment_button_course: "Aloita ilmainen kokeilu saadaksesi koko kurssin",
        payment_request_modal_cancel: "Peruuta",
        premium_valid: "tilaus on voimassa",
        premium_why: "Miksi me?",
        premium_why_des:
            "AI säästää sinulta tunteja googlaamisessa, toistamisessa, pitkien lukemisten ja ei-informatiivisten YouTube-videoiden katsomisessa. Se oppii jatkuvasti tietojesi avulla.",
        premium_why_call:
            "Intohimosi löytäminen aikaisemmin vaikuttaa dramaattisesti siihen, missä olet 15 vuoden kuluttua. Se voi maksaa sinulle tuhansia dollareita vuodessa, terveys- ja mielenterveysongelmia, tai siitä voi tulla onnellinen menestystarina.",

        //notifications
        notif_copy_event_link_description:
            "Lähetä linkki ystävillesi chatissa, ja he voivat liittyä luokkaan.",
        notif_copy_event_link_workspace:
            "Lähetä linkki oppilaillesi ja kollegoillesi chatissa, ja he voivat liittyä tähän kouluun",
        notif_copy_link_title: "Linkki kopioitu leikepöydälle",
        notif_invite: "Olemme lähettäneet kutsun jäsenillesi",
        notif_copy_link_description:
            "Pidätkö siitä? Näytä se ystävillesi tai oppilaillesi!",
        notif_achieve_subject: "Olet avannut uuden taidon:",
        notif_achieve_theme: "Olet avannut uuden taidon:",
        notif_achieve_theme_skills: "Taitojen kartta",
        notif_quiz_creating:
            "Testiä luodaan… Se voi kestää 40 sekuntia. Odota loppuun asti.",

        // event card
        event_card_button_join_room: "Liity ⚡",
        event_card_button_joined: "Liittynyt 😊",

        // tabs
        tab_my_tutorial: "Omat oppitunnit & testit",
        tab_user_tutorial: "Käyttäjän oppitunnit",
        tab_subject_tutorial: "Uudet oppitunnit datan mukaan",
        tab_subject_tutorial_new: "Uudet oppitunnit",
        tab_tag_tutorial: "Oppitunnit tagin mukaan",
        tab_ai_mentor: "AI Chat",
        tab_ai_course: "AI Kurssi",
        tab_ai_test: "Testi",
        tab_tutorial_top: "Top",
        tab_tutorial_featured: "Esillä",

        //ai
        ai_mentor_place:
            "Kysy uratavoitteista tai tämän päivän haasteista",
        ai_course_des:
            "Rakenna oma robottisi Pythonilla, käyttäen tekoälyä, koneoppimista ja OpenAI GPT-4:ää.",
        ai_course_channel:
            "UX/UI-suunnittelu mobiilisovelluksille, verkkosivuille ja peleille",
        ai_test_des:
            "Testaa taitojasi itse tai oppilaillesi. Kirjoita mitä haluat oppia, ja tekoäly luo Quizin. Älä unohda valita taitotasoa.",
        ai_test_place:
            "Kirjoita taito, lisää uratavoite tai tieto, jonka haluat tarkistaa",
        ai_popup_example: "Esimerkki",
        ai_popup_steps: "Askeleet",
        ai_popup_code: "Koodi",
        ai_popup_facts: "Faktat",
        ai_popup_video: "Video",
        ai_popup_image: "Kuva",

        // task
        answer_link_event: "😎 vain tilaajille 😎",
        task_try_again: "Virheistä oppii! Korjataan se",

        // forms
        form_theme_error_message: "Valitse järkevä aihe",
        form_theme_placeholder: "Tunnilla parannetut taidot",
        form_title_task_error_message: "Kuvaile, mitä aiot tehdä",
        form_title_task: "Otsikko",
        form_title_prompt: "Oppitunnin kehote",
        form_step_prompt: "Askeleen kehote",
        form_description_task_placeholder:
            "Lisää kuvaus, muistiinpanosi, ratkaisu ja esimerkit.",
        form_video_placeholder: "Linkki video-oppaaseen YouTubessa tai Vimeossa",
        form_add_timestamp: "Lisää aikaleima",
        form_text_question_answer_placeholder: "Lisää käytännön haaste AI-tarkistuksella",
        form_is_free_label: "Ilmainen",
        form_is_draft: "Luonnos",
        form_is_autogeneratte: "Autogeneroi",
        form_is_steps: "Askeleet",
        form_button_save: "Tallenna",
        form_button_add_task: "Julkaise",
        form_button_save_answer: "Tallenna",
        form_add_comment: " Onko sinulla kysymys? Kysy täällä",
        form_button_add_comment: "Lisää kommentti 🙌",
        form_error_add_comment: "Hups, kenttä on tyhjä",
        form_cover_title: "Lataa kuva",
        form_cover_error: "Kuva on liian suuri. Ole hyvä ja optimoi se tai käytä toista.",
        form_field_is_right: "Oikein?",
        form_add_new_answer: "Lisää vaihtoehto",
        form_remove_question: "Poista tämä vaihe",
        form_add_question: "Lisää vaihe",
        form_remove_task: "Poista oppitunti ikuisesti",
        form_add_task_to_event: "Lisää uusi oppitunti",
        form_field_is_required: "Kenttä on pakollinen",
        form_one_is_right: "Yksi kenttä on merkittävä oikeaksi",
        form_min_one_is_right: "Vähintään yhden kentän on oltava merkitty oikeaksi",
        form_question_is_required: "Kysymyksen on sisällettävä vähintään yksi vastaus",
        form_question_label: "Lisää kuvaus tai kysymys",
        form_explanation_label: "Lisää sisällön tyyppi ja selitys",
        form_task_create_title: "Luo oppitunti",
        form_task_edit_title: "Muokkaa oppituntia",
        form_task_edit_add_tag_placeholder: "Oppitunnin tagit",
        form_task_edit_add_tag_button: "Lisää uusi tagi",
        form_task_max_tags_limit_error: "Voit valita {count} tagia tai vähemmän",

        // backend error
        backend_error: "Jotain meni vikaan, yritä myöhemmin uudelleen.",

        //auth from
        auth_form_title: "Kirjaudu sisään",
        auth_youtube_form_title: "Lisää kiinnostuksesi YouTubesta",
        auth_youtube_form_description: "Luomme henkilökohtaisen taitokarttasi ja ennustamme intohimon perustuen suosikkivideoihisi YouTubessa.",
        auth_youtube_form_description2: "Tutki intohimoasi suosikkivideosi perusteella YouTubessa. Valitse mikä tahansa ura ja kehitä sitä tullaksesi Kaikkien Aikojen Parhaaksi: suorita oppitunteja, liity verkkokursseille ja julkaise omaa tietämystäsi.",
        auth_youtube_form_description3: "ja näe henkilökohtainen taitokartta ammattiennusteella.",
        auth_form_secondary1: "Kuinka käsittelemme tietoja: ",
        auth_form_secondary2: "ja ",
        auth_form_notify: "Saa ilmoituksia osaamisen kehittämisen tavoista",

        // result
        result_right_answer: "oikein",
        result_wrong_answer: "väärin",

        //skills
        skills_my: "← erikoistumisesi",
        skills_learn_my: "Testaa ja opi mitä tahansa taitoa",
        skills_des: "värikkäät tähdet ovat oppimiasi taitoja ",
        skills_result_title: "Löysimme {totalVideo} YouTube-videota, joista pidit",
        skills_result_free_title: "{freePercent}% tarkkuudella",
        skills_result_free_text: "Ilmaisversiossa käsittelemme vain <b>{allComparedVideo} näistä videoista</b> ja esitämme <b>{matchedVideo} kiinnostustasi </b>, jotka vastaavat taitokantaamme.",
        skills_result_free_text_2: "Ei tarpeeksi tietoa käsiteltäväksi.",
        skills_result_free_text_3: "Ilmaisversiossa käsittelemme vain {allComparedVideo} aiemmin tykättyä videota. Saadaksesi yksityiskohtaisen raportin, kuten kaikki inspiroivat videot YouTubessa kuukauden ajan, tule takaisin ja testaa kiinnostuksesi uudelleen.",
        skills_result_paid_title: "{paidPercent}% tarkkuudella",
        skills_result_paid_text_1:
            "Maksetussa suunnitelmassa käsittelemme ★kaikki tietosi , mahdollisuudella ★ muokata taitojasi manuaalisesti ja ★ suorittaa lisätestejä saadaksesi vähintään 200 yhtäläisyyttä kiinnostuksiesi ja tietokantamme välillä.",
        skills_result_paid_text_2:
            "Tässä tapauksessa ennustuksemme olisi jopa 80% tarkka.",
        skills_result_free_label: "Ilmainen testiversio",
        skills_result_paid_label: "Päivitetty suunnitelma ${price}",


        //careers
        career_title: "uraottelut, jotka vastaavat taitojasi:",
        career_des: "Uran Kuvaus",
        career_select_skills: "Valitse taitosi",
        career_btn_show: "Näytä ",
        career_btn_upgrade: "Aloita ilmainen 3 päivän kokeilu nähdäksesi ",
        career_btn_all: "kaikki vastaavat urat↓",
        career_btn_skills: "uran taidot, jotka opit",
        career_buy_des:
            "Tutustu taitoihin, jotka vastaavat tätä uraa. Testaa tietosi ja hanki henkilökohtaisia kursseja oppiaksesi puutteelliset taidot 🚀.",
        career_btn_proceed: "Jatka oppimista",
        career_btn_start_career: "Opi puuttuvat taidot tässä urassa",

        // meta
        meta_title_default: "Henkilökohtainen tekoälymentorisi, joka auttaa löytämään uuden uran",
        meta_title_default_short: "Henkilökohtainen tekoälymentorisi, joka auttaa löytämään uuden uran",
        meta_title_rating: "Käyttäjien arvostelu Unschoolerissa kolikoilla. ",
        meta_title_courses: "Tekoälyverkkokurssit Unschooler.me-sivustolla, jota tukee GPT-4 omalla videogeneraattorilla. Opettele mitä tahansa taitoa, luo projekteja ja saavuta uratavoitteesi.",
        meta_title_policy: "Tietosuojakäytäntö Unschoolerissa",
        meta_title_terms: "Käyttöehdot Unschoolerissa",
        meta_task_title: "opetustunti Unschoolerissa",
        meta_event_title: "Verkkokurssi Unschoolerissa",
        meta_my_account: "Unschooler - oma tili",
        meta_programs: "Tutustu aiheisiin omaan tahtiisi ja tallenna löydöksesi.",
        meta_default_description: "Interaktiiviset tekoälyvideokurssit visailuineen ja käytännön tehtävineen, jotka on luotu mihin tahansa kysymykseesi ja tiedostoillesi",
        meta_description_default_primary: "Interaktiiviset tekoälyvideokurssit visailuineen ja käytännön tehtävineen, jotka on luotu mihin tahansa kysymykseesi ja tiedostoillesi",
        meta_description_courses: "Luo verkossa tekoälyvideokursseja mille tahansa uratavoitteelle askel-askeleelta oppitunneilla ja visailuilla. Jaa ne opiskelijoillesi.",
        meta_description_rating: "Kolikot ovat virtuaalivaluuttaa, jonka ansaitset ja käytät uuden tiedon hankkimiseen. Jaa ja kerää sitä: suorita visailuja, julkaise tuloksesi ja opetusohjelmat, kerää tykkäyksiä niistä, ilmoittaudu kursseille ja luo omiasi.",
        meta_description_policy: "Unschooler on koulutusalusta tekoälyllä tuotettuihin online-videokursseihin kouluttajille, yliopistoille ja kouluille.",
        meta_description_terms: "Unschooler on koulutusalusta tekoälyllä tuotettuihin online-videokursseihin kouluttajille, yliopistoille ja kouluille.",
        meta_description_terms_mentor: "Unschooler on koulutusalusta tekoälyllä tuotettuihin online-videokursseihin kouluttajille, yliopistoille ja kouluille.",

        // phone
        phone_remainders: "WhatsApp-muistutukset",
        phone_desciption: "Lähetämme sinulle oppimistehtäviä ja muistutuksia WhatsAppissa. Ei roskapostia tai mainoksia, vain sinun maksamaasi tai kokeiluversioon liittyvää tietoa.",
        phone_placeholder: "Puhelinnumero",
        phone_button_label: "Tallenna",
        show_more: "Näytä lisää",

        // google
        google_api_login: "Valtuuta YouTubeen",
        bookmark: "Kirjanmerkki",
        ask_video: "Pyydä videota",
        payment_button_create: "Luo kurssisi",
        start: "Aloita ",
        event_start_learning: "Aloita oppiminen",
        notif_typing_loader__message: "3-8 sekuntia",

        curriculim_regenerate: "Luo suunnitelma uudelleen, jos et pidä siitä ↓",
        curriculim_generate: "Luo kurssisuunnitelmasi",
        save_notes: "Tallenna muistiinpanosi",

        // forms
        form_allow_answer_placeholder: 'Seuraavan oppitunnin ID "345"',
        quiz_generate: "Luo testi",
        summary: "Näytä yhteenveto",
        summary_hide: "Piilota yhteenveto",
        course: "kurssi",
        quiz: "tietovisa",
        add_courses_btn: "Lisää kaikki kurssisi",
        add_creator: "Lisää luoja",
        course_creators: "Kurssin luojat:",
        students: "opiskelijat",
        leave: "Poistu",
        last_questions: "Omat oppitunnit, testit ja chatit",
        login_members: "Kirjaudu jäsenille",
        sign_to_join: "Kirjaudu tähän kouluun",
        load_more: "lataa lisää",
        youtube_channel: "YouTube-kanavasi ID",
        intro: "Luo oma video tai upota YouTubesta ",
        continue: "Jatka",
        generate_video: " Luo oppitunti sisällöstäsi",
        ask_video_placeholder: "Pyydä videota, jos et ymmärrä jotakin",
        search_string: "Hae YouTubesta",
        form_text_challenge: "Haaste",
        form_text_videosum_placeholder: "Automaattisesti luotu videon yhteenveto saatavilla vain, jos videossa on tekstitykset",
        form_text_data_title: "Kehote: Oppimistavoitteet, tulokset ja arvioinnit",
        form_text_data_placeholder: "Kuvaile saamaasi sisältöä, liitä mikä tahansa artikkeli tai muistiinpanot oppitunnin luomiseksi tekstistä. Maksimissaan 50 000 merkkiä. ",
        ////fdsf
        form_text_learning: "Lähteen yhteenveto ",
        form_text_learning_placeholder: "Kuvaile saamaasi sisältöä",
        form_text_description: "Kuvaus",
        form_text_step: "Vaihe",
        form_text_step_order: "Muuta kysymysten järjestystä",
        published: "Julkaistu ",
        learn: "Opi",
        event_preenroll: 'Liity kurssille ja tilaa päivittäiset tehtäväilmoitukset',
        event_preenroll_description: 'Suorita päivittäisiä tehtäviä ja saa tekoälyltä palautetta. Työstä projektia portfoliollesi ja suorita arviointeja.',
        event_enroll_course: 'Liity',
        event_moneyback: 'Hinta:',
        event_you_in: "Olet liittynyt kurssille!",
        delete_this_step: "Poista vaihe",

        generate_subtitles: 'Luo tekstitykset tälle oppitunnille',
        progress_description_message: 'AI luo kuvauksen ja oppimisaskeleet. Tietojasi ei käytetä AI:n kouluttamiseen.',
        progress_plan_generate_message: 'AI luo henkilökohtaisen suunnitelmasi.',
        progress_create_question_message: 'Askeleet luotu, joiden mukaan saavutat tavoitteen.',
        progress_create_images_message: 'Kuvitukset luodaan…',
        progress_check_result_message: 'Ratkaisuasi tarkistetaan...',
        progress_subtitle_generation_message: 'Tekstitysten luonti...',
        progress_update_database_data: 'Oppitunti luodaan...',
        connect_my_youtube_channel: 'Oma kanavani',
        connect_another_channel: 'Valitse toinen kanava',
        connecting_to_youtube_channel: 'Yhdistetään YouTube-kanavaan',
        progress_chunks: 'Videoklipit luodaan...',
        progress_chunk: 'Videoklippi luodaan...',
        progress_audio: 'Ääninarratiivi luodaan...',
        progress_images: 'Kuvia luodaan...',
        progress_video_saving: 'Videoluonnoksen tallentaminen...',

        embed_modal_title: 'Upota brändätty kurssi alustallesi',
        embed_copy_title: 'Kopioi koodi',
        embed_copy_text: 'Koodi kopioitu leikepöydälle',
        copy_label: 'Kopioi',
        cancel_label: 'Peruuta',
        footer_educators: 'Ratkaisu opettajille',
        premium_start: "Aloita",
        premium_creator: "Luoja",
        premium_university: "Yliopisto",
        premium_creator_description: "Luo kursseja sisällöstäsi",
        premium_university_description: "Integroi Unschooler alustallesi",
        upgrade: "Päivitä",
        contact_sales: "Ota yhteyttä myyntiin",
        features: "Kaikki ominaisuudet",
        custom: "Mukautettu",

        solution_placeholder: "Anna ratkaisusi tähän tehtävään",
        solution_send: "Lähetä ratkaisu",
        learning_type: "Valitse, miten haluat oppia",
        learning_text: "Lue tekstiä ja esimerkkejä",
        learning_project: "Harjoittele pienellä projektilla",
        learning_video: "Etsi video",
        learning_check: "Tarkista ymmärryksesi",
        learning_info: "Valitse infografiikka",
        learning_quiz: "Pelaa visailua",

        //
        tab_ai_lesson: "AI-opetus",
        tab_ai_channel: "YouTube-kanava",
        tab_ai_vimeo: "Vimeo",
        ask_placeholder_def: "Kysy mitä tahansa",
        ask_placeholder_yt: "https://www.youtube.com/watch?v=FCqkUi1-7S0",
        question_regenerate: "puhdas",
        question_add: "Lisää lisää tietokilpailuja, vaiheita videoita",

        header_courses: "AI-videokurssit opettajille, alustoille ja yrityksille",
        upload_video: "Lataa mp4, max 300Mb 30 min",
        ai_course_promo: "Luo kurssi mihin tahansa tavoitteeseen",
        ai_mentor_promo: "Kysy urahaasteista ja uusista taidoista",
        ai_test_promo: "Testaa mitä tahansa taitojasi, jaa opiskelijoiden kanssa",
        ai_lesson_promo: "Muunna sisältösi oppitunniksi",
        ai_channel_promo: "Yhdistä YouTube-kanava ja luo kursseja sisällöstäsi",

        tab_ai_video: "YouTube/Vimeo-linkki",
        tab_ai_text: "Teksti",
        tab_ai_mp4: "Video",
        tab_ai_link: "URL",
        tab_ai_pdf: "PDF",

        //checkout
        checkout_subscription: 'Kuukausitilaus',
        checkout_weekly_subscription: 'Viikkotilaus',
        checkout_guide_title: 'Hanki henkilökohtainen uraopas',
        checkout_enroll_title: 'Ilmoittaudu kurssille',
        checkout_thanks: 'Kiitos maksusta',
        checkout_booking_confirmation:
            'Lähetämme vahvistuksen varauksestasi sähköpostitse - ',
        checkout_success_purchase: 'ostoit pääsyn Premium-klubiin',
        checkout_link_for_activation:
            'Lähetämme lahjan aktivointisivun linkin antamaasi sähköpostiosoitteeseen maksun yhteydessä.',
        checkout_check_other_lessons: 'Tarkista muut oppitunnit',
        checkout_go_to_skills: 'Mene testaamaan kiinnostuksia YouTubessa',

        // Stripe
        stripe_student_name: "Opiskelijan etu- ja sukunimi",
        stripe_student_email: "Opiskelijan sähköposti",
        stripe_student_phone: "Opiskelijan puhelin",
        stripe_accept: 'Hyväksyn',
        stripe_accept_terms: 'Käyttöehdot',
        stripe_accept_terms_confirm: 'ja vahvistan, että tietokoneeni tai puhelimeni vastaa',
        stripe_technical_requirements: 'Tekniset vaatimukset',
        stripe_input_card_number: 'Anna luottokorttitietosi',
        stripe_pay: 'Maksa',
        stripe_accept_error: 'Varmista, että työpaikkasi sopii online-tunneille.',
        stripe_error_email_message: "Ei näytä oikealta sähköpostilta!",
        stripe_error_phone_message: 'Tarkista puhelinnumero',

        form_text_course_title: "Oppimistavoite",
        form_workspace_placeholder: "Koulusi nimi",
        form_workspace_description: "Koulusi kuvaus",
        form_workspace_create: "Tallenna koulun asetukset",
        form_workspace_logo: "Lataa logo",
        form_workspace_cover: "Lataa kansi",
        form_workspace_description_placeholder: "Kirjoita tämän työtilan tarkoitus",
        form_link_placeholder: "Verkkosivun URL: AI analysoi sen ja luo oppitunnin.",
        form_link_placeholder_input: "https://en.wikipedia.org/wiki/First_class_travel",

        free: "ilmainen",
        translate_modal_title: 'Käännä tämä kurssi mihin tahansa kieleen. Kopioimme sen ja korvaamme tekstit valitulla kielellä:',
        translate_btn: 'Käännä',

        event_add_calendar: "Lisää kalenteriin",
        event_added_calendar: "Lisätty kalenteriin",
        event_add_calendar_title: "Muistutukset on lisätty kalenteriisi",
        event_add_calendar_description: "Muistutamme sinua joka päivä urasi kehittämisestä",
        event_connect_to_call: 'Liity puheluun',

        create_your_school: "Luo koulusi",
        setup_your_school: "Aseta koulusi työtila",
        invite: "Kutsu",
        download: "Lataa",
        translate: "Käännä",
        add_your_content: "Tiedon lähde",
        course_selling: "3. Kurssin hinta (kursseille, joissa on henkilökohtaista videosisältöä)",
        form_text_course_plan: "Tarkista kurssisi oppimissuunnitelma, poista aihe tai luo uudelleen",

        loader_generic: "luodaan, kestää 1-2 min",
        loader_quiz: "visa luodaan ja tallennetaan",
        loader_task: 'Oppitunti luodaan, odota 1 minuuttia',
        loader_step: 'AI luo askelta ',
        loader_step_contentquiz: 'AI luo askeleen oppaan, joka auttaa sinua saavuttamaan tavoitteesi visan avulla.',
        loader_step_quiz: 'AI luo askeleen oppaan, joka auttaa sinua saavuttamaan tavoitteesi visan avulla.',
        loader_nextstepai: 'AI luo kuvauksen ja askeleet. Tietojasi ei käytetä AI:n kouluttamiseen.',
        loader_nextstepai_async: 'Seuraava askel luodaan, odota latauksen päättymistä 1 min…',
        loader_video: 'AI kerää aiheeseen liittyvät olennaisimmat YouTube-videot.',
        loader_assess: `AI luo käytännön haasteen, joka auttaa sinua saavuttamaan tavoitteesi.`,

        tab_workspace_tutorial: "Julkaistut oppitunnit & testit",
        tab_workspace_tutorial_draft: "Omat testiluonnokset",
        title_task: "Harjoitellaan",
        select_text: "Valitse teksti",
        btn_skip: "Ohita",
        ai_popup_explain: "Selitä",
        edit: "Muokkaa",
        ask_ai: "Pyydä AI:tä lisäämään jotain",
        loader_translate: "AI kääntää tämän kurssin kaikkine vaiheineen. Tämän prosessin jälkeen sinut ohjataan uudelle kurssille.",
        ai_generate_tasks_button: "Luo kurssin sisältö",
        ai_generation_tasks: "Kurssin luominen",
        click_upload: "Napsauta ladataksesi",
        feedback_field: "  Mitä jäi puuttumaan tästä ohjeesta?",
        form_text_data_file: "Lataa pdf-tiedostosi: otamme ensimmäiset 30 000 merkkiä ja luomme oppitunnin.",

        tab_event_published: "Julkaistut Kurssit",
        tab_event_drafts: "Luonnokset",
        tab_events_my: "Omat kurssit",
        tab_events_user: "Kurssit",
        tab_events_all: "Kaikki kurssit",
        tab_event_by_subjectIds: "Esitellyt kurssit",

        vimeo_add_desc: "Lisää linkki Vimeo-kansioosi videoiden etsimiseksi",
        vimeo_add: "Lisää Vimeo-kansio",
        vimeo_your: "Vimeo-kansiosi",
        vimeo_change: "Vaihda Vimeo-kansiota",

        create_event_tab_1: "Kurssin Lähde",
        create_event_tab_2: "Muokkaa Oppitunteja",
        create_event_tab_3: "Julkaise & Myy kurssi",

        search_placeholder: 'Hae',
        search_result_title: 'Hakutulokset pyynnöstä',
        search_result_not_found: 'Tuloksia ei löytynyt',


        // new
        wrksp_add_section: 'Lisää kurssin osio',
        wrksp_add_section_plchldr: "Kirjoita otsikko tähän",
        wrksp_add_section_title: "Otsikko",
        form_workspace_custom_domain: "Mukautettu verkkotunnus",
        form_workspace_add_records: "Lisää A- ja TXT-tietueita verkkotunnuksesi rekisteriin:",
        form_workspace_content: "Sisältö",
        form_workspace_host: "Tuleva aliverkkotunnus",
        form_workspace_domain: "Verkkotunnus",
        form_workspace_sections: "Kurssin osiot",
        form_workspace_invite: "Kutsu jäseniä",
        form_workspace_send_invite: "Lähetä kutsu",
        participants_list_title: " opiskelijaa on liittynyt tälle kurssille",
        learning_time: "Oppimisaika",
        form_lesson_tab: 'Oppitunnin lähde',
        form_content_tab: 'Sisältö',
        form_display_tab: 'Näyttö',
        feedback_easy: 'liian helppo',
        feedback_abstract: 'liian abstrakti',
        feedback_wordy: 'liian sanallinen',
        feedback_steps: 'lisää vaiheita',

        achievements: "Kaikki saavutukseni",

        workspace_title_name: 'Brändäys & Mukautettu verkkotunnus',
        workspace_title_content: 'Verkkosivun Ulkoasu',
        workspace_title_payments: 'Maksut',
        form_workspace_settings: "Koulun Asetukset",
        auth_form_title_signup: "Luo uusi tili",

        workspace_host_required: 'Isäntä on pakollinen',
        workspace_host_is_not_valid: 'Isäntä ei ole pätevä!',
        workspace_host_extra: 'Isännän on sisällettävä vain pieniä kirjaimia ilman välilyöntejä (voi sisältää numeroita ja väliviivoja).',
        workspace_host_exist: 'Sama isäntä on jo olemassa',
        workspace_domain_status: 'Tila',
        workspace_domain_updates: '(päivityksiä 24 tunnin sisällä)',
        workspace_layout_message: 'Hallitse opiskelijoiden huomiota taitoryhmällä. Voit määrittää ne ja muuttaa niitä myös pääsivulla.',
        workspace_domain_is_not_valid: 'Virheellinen toimialueen nimi',
        workspace_domain_is_not_extra: 'Tämä kenttä on valinnainen. Toimialueen on sisällettävä vain pieniä kirjaimia (voi sisältää väliviivoja ja pisteitä). Esimerkkejä: ',

        stripe_connect_label: 'Yhdistä Stripeen',
        stripe_connect_existed_account: 'Sinulla on yhdistetty Stripe-tili.',
        stripe_connect_existed_text_1: 'Yhdistä Stripe-tilisi aloittaaksesi maksujen vastaanottamisen kurssimyynneistä',
        stripe_connect_existed_text_2: 'Stripen käyttöönotto on nopeaa eikä se veloita kuukausimaksuja kuten useimmat maksunvälittäjät, vain pienen maksun per transaktio.',
        stripe_connect_existed_text_3: 'Sinun on luotava ja ylläpidettävä Stripe-tiliäsi, jos sinulla ei ole sitä jo.',
        stripe_connect_existed_text_4: 'Sinun on käsiteltävä takaisinmaksut ja kaikki asiakaspalveluun liittyvät ongelmat. Meillä ei ole kontrollia tai vastuuta asiakkaidesi maksuista.',

        //translate_to_arrange
        ai_chat_questin_text1: 'Minkä ohjelmointikielen opettelu kannattaa aloittaa pelejä luodaksesi?',
        ai_chat_question_text2: 'Mitä tehtäviä front-end kehittäjän päivään kuuluu?',
        login_button: 'Kirjaudu sisään sähköpostilla',
        reset_password_button: 'Nollaa salasana',
        email_input_text: 'Sähköposti',
        password_input_text: 'Salasana',
        enter_password_warning: 'Syötä salasanasi',
        enter_email_warning: 'Syötä sähköpostiosoitteesi',
        embed_button: 'upota',
        add_member_button: 'Lisää jäsen',
        enter_title_warning: 'Syötä otsikko!',
        title_input_text: 'Otsikko',
        Change_title: 'Muuta profiilitietoja',
        invite_subtitle: 'Koulusi on valmis, kirjaudu sisään ja kutsu oppilaasi ',
        welcome_title_text: 'Tervetuloa {workspace} kouluun',
        access_information_start: 'Pääsy',
        vimeo_folder: 'vimeo-soitin',
        sign_to_join_signup: 'Rekisteröidy',

        congrats: "Onnittelut! Jatka hyvää työtä ja saavuta tavoitteesi!",
        steps: "Vaiheittainen opas:"
    },
};
