/* eslint-disable import/no-anonymous-default-export */
import { LOCALES } from "../locales";

export default {
    [LOCALES.CHINESE]: {
        // common
        auth_button: "用谷歌登录",
        auth_button_short: "登录",
        skills: "技能",
        careers: "职业",
        month: "月",
        terms: "条款",
        policy: "隐私政策",
        policy_content: "内容政策",

        //footer
        footer_skill_map: "技能图谱",
        footer_career_explorer: "职业探索器",
        footer_courses: "基于项目的在线课程",
        footer_pricing: "定价",

        //btns
        more: "更多",
        share: "分享",
        junior: "简单",
        middle: "中等",
        senior: "困难",

        // header
        header_profile: "专业化：",
        nav_tutorials: "职业生涯",
        nav_skills: "技能",
        nav_premium: "我的计划",
        nav_upgrade: "升级",
        nav_ask: "学习",
        nav_exit: "登出",
        nav_workspace: "教学",
        program_tutorial: "选择您喜欢的主题：",
        edit_user_label: "我的个人资料",
        user_name_label: "用户名",
        user_picture_label: "用户头像",

        //profile
        profile_moto: "AI驱动视频课程，助您实现个人职业目标。",
        profile_description:
            "随时随地在几分钟内学习所需的一切。找到最适合的职业。生成带有视频、测验和AI反馈的个人课程，学习缺失的技能。",
        profile_reccomended: "推荐职业",
        profile_learn: "与AI导师一起学习，获得",
        profile_map: "您的技能图谱",
        profile_list_suggested: "以及建议的列表",
        profile_upgrade_skills:
            "专业化是您最常参与的知识领域。在这里您已经学习",
        profile_specialisation_times: "次数",
        profile_specialisation_my: "我的专业化",
        profile_your_learned: "您学到了",
        profile_matching: "与您的技能相匹配",
        add_explainer_short: "将课程链接到本课程",

        //skills
        skills_update_interest: "更新YouTube技能",
        skills_test_interest: "在YouTube上找技能",

        //event
        event_create: "从头开始创建课程",
        event_finish: "离开直播室",
        event_proceed: "直播室",
        event_change: "编辑课程",
        event_upgrade: "开始免费试用以编辑",
        event_btn_friend: "与学生分享",
        event_tasks_description: "您将学到",
        event_result: "结果：您将创建",
        event_need: "您将需要",
        event_how: "工作原理",

        create_event_title_edit: "编辑课程",
        create_event_title_create: "创建课程",
        create_event_remove_event: "永久删除课程",
        create_event_title_label: "课程标题",
        create_event_title_message: "课程必须有一个标题",
        create_event_subject_label: "选择课程标签以进行搜索和组织",
        create_event_subject_extra:
            "在聊天中发送未找到的标签，我们将在15分钟内添加",
        create_event_subject_message:
            "没有标签的事件将不会被创建",
        create_event_cost_label: "1个学生的价格（美元）/ 您从1个学生那里获得的",
        create_event_save: "保存课程并退出",

        // event set date
        event_set_date_every_week: "每个{day}在{time}",
        event_set_date_exist: "事件已存在",
        event_set_date_added: "事件已添加",
        event_set_date_title: "日程",
        event_set_date_description:
            "没有日期和时间的课程将被添加到“公告”部分。此选项适用于集体。",
        event_set_date_schedule: "从{date}开始每个{day}，{time}",
        event_set_date_remove_item: "删除课程",
        event_set_date_add_date: "添加日期和时间",
        event_set_date_date: "日期",
        event_set_date_time: "时间",
        event_set_date_dont_repeat: "不重复",
        event_set_date_repeat: "每周重复",

        group_groups: "我的学校及其为学生提供的课程：",
        group_tutorial: "创建您的课程：",
        group_soon: "特色课程，免费试用 ↓",
        group_soon_description: "我们用户创建的最有趣的课程。你可以免费学习。",

        participants_list_subsicribe: "订阅",

        premium: "高级",
        premium_pro: "专业版",
        premium_your: "您的计划",
        premium_description: "测试兴趣并弥补缺失的技能",
        premium_pro_description: "为教育工作者创建您的学校并销售课程",
        premium_moneyback: "3天免费试用",
        payment_premium_monthly: "开始免费试用",
        payment_title: "升级您的计划",
        payment_button: "开始免费试用",
        payment_button_course: "开始免费试用以创建课程",
        payment_request_modal_cancel: "取消",
        premium_valid: "订阅有效期至",
        premium_why: "为什么选择我们？",
        premium_why_des: "我们的AI能节省您在谷歌上搜索的时间，重复您已知的事物以及观看长篇大论和信息含量不高的YouTube视频。它会根据您的数据不断学习。",
        premium_why_call: "更早地找到您的热情所在，将极大影响您在15年后的位置。这可能每年花费您数千美元，导致健康和心理问题，或者成为充满成功和渴望的快乐旅程。",

        notif_copy_event_link_description: "将链接发送给您的朋友在聊天中，他们就可以加入课堂。",
        notif_copy_event_link_workspace: "将链接发送给您的学生和同事在聊天中，他们就可以加入这个学校",
        notif_copy_link_title: "链接已复制到剪贴板",
        notif_invite: "我们已向您的成员发送邀请",
        notif_copy_link_description: "喜欢吗？展示给你的朋友或学生！",
        notif_achieve_subject: "您解锁了一项新技能：",
        notif_achieve_theme: "您解锁了一项新技能：",
        notif_achieve_theme_skills: "您的技能图谱",
        notif_quiz_creating: "测试正在创建中... 这可能需要40秒。请耐心等待结束。",

        event_card_button_join_room: "加入 ⚡",
        event_card_button_joined: "已加入 😊",

        tab_my_tutorial: "我的课程和测试",
        tab_user_tutorial: "用户课程",
        tab_subject_tutorial: "根据数据的新课程",
        tab_subject_tutorial_new: "新课程",
        tab_tag_tutorial: "按标签的课程",
        tab_ai_mentor: "AI 聊天",
        tab_ai_course: "AI 课程",
        tab_ai_test: "测试",
        tab_tutorial_top: "热门",
        tab_tutorial_featured: "特色",

        ai_mentor_place: "询问职业目标或今天的挑战",
        ai_course_des: "使用人工智能、机器学习和OpenAI GPT-4构建自己的机器人。",
        ai_course_channel: "移动应用、网站和游戏的UX/UI设计",
        ai_test_des: "为自己或您的学生测试技能。写下您想学习的内容，AI会生成一个测验。不要忘记选择技能等级。",
        ai_test_place: "写下技能，添加职业目标或您想检查的知识",
        ai_popup_example: "示例",
        ai_popup_steps: "步骤",
        ai_popup_code: "代码",
        ai_popup_facts: "事实",
        ai_popup_video: "视频",
        ai_popup_image: "图片",

        answer_link_event: "😎 仅限订阅者 😎",
        task_try_again: "犯错误让我们变得聪明！让我们修正它",

        form_theme_error_message: "选择一个有意义的主题",
        form_theme_placeholder: "通过这节课提升的技能",
        form_title_task_error_message: "描述您将做什么",
        form_title_task: "标题",
        form_title_prompt: "课程提示",
        form_step_prompt: "步骤提示",
        form_description_task_placeholder: "添加描述、您的笔记、解决方案和示例。",
        form_video_placeholder: "链接到youtube或vimeo上的视频教程",
        form_add_timestamp: "添加时间戳",
        form_text_question_answer_placeholder: "添加具有AI检查的实际挑战",
        form_is_free_label: "免费",
        form_is_draft: "草稿",
        form_is_autogeneratte: "自动生成",
        form_is_steps: "步骤",
        form_button_save: "保存",
        form_button_add_task: "发布",
        form_button_save_answer: "保存",
        form_add_comment: "有问题吗？在这里提问吧",
        form_button_add_comment: "添加评论 🙌",
        form_error_add_comment: "哎呀，字段为空",
        form_cover_title: "上传图片",
        form_cover_error: "图片太大了。请优化它或使用其他的。",
        form_field_is_right: "正确吗？",
        form_add_new_answer: "添加选项",
        form_remove_question: "删除这个步骤",
        form_add_question: "添加步骤",
        form_remove_task: "永久删除课程",
        form_add_task_to_event: "添加新课程",
        form_field_is_required: "该字段为必填项",
        form_one_is_right: "必须将一个字段标记为正确",
        form_min_one_is_right: "至少必须将一个字段标记为正确",
        form_question_is_required: "问题必须至少包含一个答案",
        form_question_label: "添加描述或问题",
        form_explanation_label: "添加内容类型和解释",
        form_task_create_title: "创建课程",
        form_task_edit_title: "编辑课程",
        form_task_edit_add_tag_placeholder: "课程标签",
        form_task_edit_add_tag_button: "添加新标签",
        form_task_max_tags_limit_error: "您最多只能选择{count}个标签",

        backend_error: "出了些问题，请稍后再试。",

        auth_form_title: "选择语言并登录",
        auth_youtube_form_title: "从YouTube添加您的兴趣",
        auth_youtube_form_description: "我们将创建您的个人技能图谱，并根据您在YouTube上喜爱的视频预测激情。",
        auth_youtube_form_description2: "根据您在YouTube上喜爱的视频探索您的激情。选择任何职业并将其提升至最伟大的水平：完成课程，加入在线课程，并发布您的知识。",
        auth_youtube_form_description3: "并查看个人技能图谱与职业预测。",
        auth_form_secondary1: "我们如何处理数据：",
        auth_form_secondary2: "和",
        auth_form_notify: "获取关于提升技能的通知",

        // result
        result_right_answer: "正确",
        result_wrong_answer: "错误",

        //skills
        skills_my: "← 你的特长",
        skills_learn_my: "测试并学习任何技能",
        skills_des: "五彩斑斓的星星是在 中学到的技能",
        skills_result_title:
            "我们在Youtube上找到了{totalVideo}个你喜欢的视频",
        skills_result_free_title: "{freePercent}%的准确率",
        skills_result_free_text:
            "在免费版本中，我们将只处理<b>{allComparedVideo}个这些视频</b>，并展示<b>{matchedVideo}个与我们技能库相符的你的兴趣</b>。",
        skills_result_free_text_2: "数据不足，无法处理。",
        skills_result_free_text_3:
            "在免费版本中，我们将只处理你以前喜欢的{allComparedVideo}个视频。要获得详细报告，例如YouTube上一个月内所有鼓舞人心的视频，请再次回来测试你的兴趣。",
        skills_result_paid_title: "{paidPercent}%的准确率",
        skills_result_paid_text_1:
            "在付费计划中我们处理★你的所有数据，可以★手动编辑你的技能，还可以★进行额外测试，至少在你的兴趣和我们的数据库之间获得200个匹配。",
        skills_result_paid_text_2:
            "在这种情况下，我们的预测准确率可达80%。",
        skills_result_free_label: "免费测试版本",
        skills_result_paid_label: "升级计划，价格为${price}",

        //careers
        career_title: "职业与你的技能匹配：",
        career_des: "职业描述",
        career_select_skills: "选择你的技能",
        career_btn_show: "显示",
        career_btn_upgrade: "开始免费3天试用以查看",
        career_btn_all: "所有匹配的职业↓",
        career_btn_skills: "你学到的职业技能",
        career_buy_des:
            "探索与这个职业匹配的技能。测试你的知识并获得个人课程来学习盲点🚀。",
        career_btn_proceed: "继续学习",
        career_btn_start_career: "学习这个职业中缺失的技能",

        // meta
        meta_title_default:
            "个人AI导师帮助你找到新的职业",
        meta_title_default_short:
            "个人AI导师帮助你找到新的职业",
        meta_title_rating: "用户在Unschooler上按金币评分。",
        meta_title_courses:
            "Unschooler.me上由GPT-4提供支持的AI在线课程，配有YouTube视频。学习任何技能，创建项目并达到你的职业目标。",
        meta_title_policy: "Unschooler的隐私政策",
        meta_title_terms: "Unschooler的使用条款",
        meta_task_title: "Unschooler上的课程",
        meta_event_title: "Unschooler上的在线课程",
        meta_my_account: "Unschooler - 我的账户",
        meta_programs:
            "按照自己的节奏探索主题并保存你的发现。",
        meta_default_description:
            "由专业人士领导的在线课程，提供趣味性一步一步的课程，以获得未来的技能",
        meta_description_default_primary:
            "Unschooler是一个在线教育平台，提供在线课程和课程，专业人士为青少年围绕实际项目发布课程，添加逐步教学并在在线课上提供反馈。\n" +
            "每个新结果都储存在青少年的作品集中，并更新技能图谱。它作为一个自然的职业道路。",
        meta_description_courses:
            "生成带有视频和AI的在线课程，以你的个人职业目标进行逐步教学。与你的学生分享它们。",
        meta_description_rating:
            "金币是你在新知识上获得和花费的虚拟货币。分享并收集它：通过测验，发布你的结果和教程，为它们收集点赞，注册课程并创建你自己的课程。",
        meta_description_policy:
            "Unschooler是一个在线教育平台，提供在线课程和课程，专业人士为青少年围绕实际项目发布课程，添加逐步教学并在在线课上提供反馈。",
        meta_description_terms:
            "Unschooler是一个在线教育平台，提供在线课程和课程，专业人士为青少年围绕实际项目发布课程，添加逐步教学并在在线课上提供反馈。",
        meta_description_terms_mentor:
            "Unschooler是一个在线同步课程和异步UGC课程的市场。教程是带有测验和嵌入式YouTube视频的互动文章。人们展示和分享他们创建的内容，并分享很酷的学习材料。在线课程是一个封闭的视频会议室，用于小组课。它包括一系列仅供参与者使用的课程，支付，日程安排，分享学生结果的可能性，并进行学习笔记。",

        // phone
        phone_remainders: "WhatsApp提醒",
        phone_desciption:
            "我们将通过WhatsApp向你发送学习任务和提醒。没有垃圾邮件或广告，只有你付费或试用的信息。",
        phone_placeholder: "手机号码",
        phone_button_label: "保存",
        show_more: "显示更多",

        // google
        google_api_login: "在youtube上授权",
        bookmark: "书签",
        ask_video: "询问视频",
        payment_button_create: "创建你的课程",
        start: "开始",
        event_start_learning: "开始学习",
        notif_typing_loader__message: "3-8秒",

        curriculim_regenerate: "如果你不喜欢，重新生成这个计划↓",
        curriculim_generate: "生成你的课程计划",
        save_notes: "保存你的笔记",

        // forms
        form_allow_answer_placeholder: '下一课的ID“345”',
        quiz_generate: "生成测试",
        summary: "显示摘要",
        summary_hide: "隐藏摘要",
        course: "课程",
        quiz: "测验",
        add_courses_btn: "添加你的所有课程",
        add_creator: "添加创建者",
        course_creators: "课程创建者：",
        students: "学生",
        leave: "离开",
        last_questions: "最后的课程，测试和聊天",
        login_members: "会员登录",
        sign_to_join: "加入这所学校",
        load_more: "加载更多",
        youtube_channel: "你的YouTube频道ID",
        intro: "选择或搜索视频：",
        continue: "继续",
        generate_video: " 从你的内容生成课程",
        ask_video_placeholder: "如果你有不懂的可以询问视频",
        search_string: "搜索视频…",
        form_text_challenge: "挑战",
        form_text_videosum_placeholder: "视频摘要自动生成，仅当视频包含字幕时可用",
        form_text_data_title: "提示：学习目标、成果和评估",
        form_text_data_placeholder: "描述你想要获得的内容，粘贴任何文章或笔记以从文本生成课程。最多50,000个字符。",
        form_text_learning: "源内容摘要",
        form_text_learning_placeholder: "描述您希望获取的内容",
        form_text_description: "描述",
        form_text_step: "步骤",
        form_text_step_order: "更改问题的顺序",
        published: "已发布",
        learn: "学习",
        event_preenroll: '加入课程并订阅每日任务通知',
        event_preenroll_description: '完成每日任务并接收AI生成的反馈。为您的作品集工作并进行评估。',
        event_enroll_course: '加入',
        event_moneyback: '价格：',
        event_you_in: "您已加入课程！",
        delete_this_step: "删除",

        generate_subtitles: '为本课生成字幕',
        progress_description_message: 'AI生成描述和学习步骤。您的数据不会用于训练AI。',
        progress_plan_generate_message: 'AI正在生成您的个人计划。',
        progress_create_question_message: '已创建步骤，您将通过这些步骤达到目标。',
        progress_check_result_message: '正在检查您的解决方案...',
        progress_subtitle_generation_message: '字幕生成中...',
        progress_update_database_data: '教程生成中...',
        connect_my_youtube_channel: '我的频道',
        connect_another_channel: '选择其他频道',
        connecting_to_youtube_channel: '正在连接到YouTube频道',

        embed_modal_title: '将此课程嵌入到您的平台',
        embed_copy_title: '复制代码',
        embed_copy_text: '代码已复制到剪贴板',
        copy_label: '复制',
        cancel_label: '取消',
        footer_educators: '教育者的解决方案',
        premium_start: "开始",
        premium_creator: "创建者",
        premium_university: "大学",
        premium_creator_description: "从您的视频中快速生成课程",
        premium_university_description: "将Unschooler集成到您的平台",
        upgrade: "升级",
        contact_sales: "联系销售",
        features: "所有功能",
        custom: "自定义",

        solution_placeholder: "描述此任务的解决方案",
        solution_send: "发送解决方案",
        learning_type: "选择您希望的学习方式",
        learning_text: "阅读文本和示例",
        learning_project: "通过小项目练习",
        learning_video: "寻找视频",
        learning_check: "检查您的理解",
        learning_info: "选择信息图表",
        learning_quiz: "玩测验",

        // 
        tab_ai_lesson: "AI课程",
        tab_ai_channel: "YouTube频道",
        tab_ai_vimeo: "Vimeo",
        ask_placeholder_def: "提问任何问题",
        ask_placeholder_yt: "https://www.youtube.com/watch?v=FCqkUi1-7S0",
        question_regenerate: "清洁",
        question_add: "更多",

        header_courses: "面向教育者、平台和公司的AI视频课程",
        upload_video: "上传mp4，最大300Mb 30分钟",
        ai_course_promo: "为任何新目标创建课程",
        ai_mentor_promo: "询问职业挑战和新技能",
        ai_test_promo: "测试您的任何技能，与他人分享",
        ai_lesson_promo: "将您的内容转换为课程",
        ai_channel_promo: "连接YouTube频道并从您的内容生成课程",

        tab_ai_video: "YouTube/Vimeo链接",
        tab_ai_text: "文本",
        tab_ai_mp4: "视频",
        tab_ai_link: "URL",
        tab_ai_pdf: "PDF",

        // 结帐
        checkout_subscription: '每月订阅',
        checkout_weekly_subscription: '每周订阅',
        checkout_guide_title: '获取个人职业指南',
        checkout_enroll_title: '注册课程',
        checkout_thanks: '感谢您的付款',
        checkout_booking_confirmation:
            '我们将通过电子邮件向您发送预订确认 - ',
        checkout_success_purchase: '您已购买进入高级俱乐部的权限',
        checkout_link_for_activation:
            '我们将发送礼物激活页面链接到您支付时输入的电子邮件。',
        checkout_check_other_lessons: '检查其他课程',
        checkout_go_to_skills: '去用YouTube测试兴趣',

        // Stripe
        stripe_student_name: "学生的名字和姓氏",
        stripe_student_email: "学生的电子邮件",
        stripe_student_phone: "学生的电话",
        stripe_accept: '我接受',
        stripe_accept_terms: '使用条款',
        stripe_accept_terms_confirm: '并确认我的电脑或手机符合',
        stripe_technical_requirements: '技术要求',
        stripe_input_card_number: '输入您的信用卡详细信息',
        stripe_pay: '支付',
        stripe_accept_error: '请确保您的工作场所适合在线课程。',
        stripe_error_email_message: "看起来不像是正确的电子邮件！",
        stripe_error_phone_message: '请检查电话号码',

        form_text_course_title: "输入课程主题、学习成果或目标",
        form_workspace_placeholder: "您学校的名称",
        form_workspace_description: "您学校的描述",
        form_workspace_create: "保存学校设置",
        form_workspace_logo: "上传标志",
        form_workspace_cover: "上传封面",
        form_workspace_description_placeholder: "写下这个工作空间的目的",
        form_link_placeholder: "网页的URL：AI将分析它并生成课程。",
        form_link_placeholder_input: "https://en.wikipedia.org/wiki/First_class_travel",
        free: "免费",
        translate_modal_title: '将此课程翻译成任何语言。我们将复制它并用所选语言替换文本：',
        translate_btn: '翻译',

        event_add_calendar: "添加到日历",
        event_added_calendar: "已添加到日历",
        event_add_calendar_title: "通知已添加到您的日历",
        event_add_calendar_description: "我们将每天提醒您升级您的职业生涯",
        event_connect_to_call: '加入通话',

        create_your_school: "创建您的学校",
        setup_your_school: "设置您的学校工作区",
        invite: "邀请",
        download: "下载",
        translate: "翻译",
        add_your_content: "选择信息来源或添加您的内容",
        course_selling: "3. 从个人视频内容出售课程（从创作者计划开始）",
        form_text_course_plan: "查看您的学习计划，删除任何主题或重新生成",

        loader_generic: "正在生成，需要1-2分钟",
        loader_quiz: "测验已创建并保存",
        loader_task: '课程正在生成，请等待1分钟',
        loader_step: 'AI正在创建步骤',
        loader_step_contentquiz: 'AI正在创建带有测验的步骤指南，帮助您实现目标。',
        loader_step_quiz: 'AI正在创建带有测验的步骤指南，帮助您实现目标。',
        loader_nextstepai: 'AI生成描述和步骤。您的数据不会用于训练AI。',
        loader_nextstepai_async: '下一步已生成，请等待加载结束1分钟…',
        loader_video: 'AI收集此主题最相关的YouTube视频。',
        loader_assess: `AI正在创建实践挑战，帮助您实现目标。`,

        tab_workspace_tutorial: "已发布的课程和测试",
        tab_workspace_tutorial_draft: "我的测试草稿",
        title_task: "让我们练习",
        select_text: "选择文本用于",
        btn_skip: "跳过",
        ai_popup_explain: "解释",
        edit: "编辑",
        ask_ai: "让AI添加个性化课程",
        loader_translate: "AI正在翻译此课程的所有步骤。此过程之后，您将被重定向到新课程。",
        ai_generate_tasks_button: "生成整个课程",
        ai_generation_tasks: "课程生成",
        click_upload: "点击上传",
        feedback_field: "  这个教程遗漏了什么？",
        form_text_data_file: "上传您的PDF：我们将取前30000个字符并生成课程。",

        tab_event_published: "已发布课程",
        tab_event_drafts: "草稿",
        tab_events_my: "我的课程",
        tab_events_user: "课程",
        tab_events_all: "所有课程",
        tab_event_by_subjectIds: "特色课程",

        vimeo_add_desc: "添加您的Vimeo文件夹链接以搜索视频",
        vimeo_add: " 添加Vimeo文件夹",
        vimeo_your: "您的Vimeo文件夹",
        vimeo_change: "更改Vimeo文件夹",

        create_event_tab_1: "课程来源",
        create_event_tab_2: "编辑课程",
        create_event_tab_3: "展示课程",

        search_placeholder: '搜索',
        search_result_title: '按请求的搜索结果',
        search_result_not_found: '未找到结果',

        wrksp_add_section: '添加事件部分',
        wrksp_add_section_plchldr: "在此输入标题",
        wrksp_add_section_title: "标题",
        form_workspace_custom_domain: "自定义域名",
        form_workspace_add_records: "在您的域名注册处添加 A 和 TXT 记录：",
        form_workspace_content: "内容",
        form_workspace_host: "期望的主机",
        form_workspace_domain: "域",
        form_workspace_sections: "课程部分",
        form_workspace_invite: "邀请成员",
        form_workspace_send_invite: "发送邀请",
        participants_list_title: " 学生加入了此课程",
        learning_time: "学习时间",
        form_lesson_tab: '课程来源',
        form_content_tab: '内容',
        form_display_tab: '显示',
        feedback_easy: '太简单',
        feedback_abstract: '太抽象',
        feedback_wordy: '太啰嗦',
        feedback_steps: '更多步骤',

        workspace_title_name: '品牌和自訂域名',
        workspace_title_content: '網頁佈局',
        workspace_title_payments: '付款方式',
        form_workspace_settings: "學校設置",
        auth_form_title_signup: "建立新帳戶",

        workspace_host_required: '主機為必填項',
        workspace_host_is_not_valid: '主機無效',
        workspace_host_extra: '主機只能包含小寫字母，不能包含空格（可以包含數字和連字號）。',
        workspace_host_exist: '同一主機已存在',
        workspace_domain_status: '地位',
        workspace_domain_updates: '（24小時更新）',
        workspace_layout_message: '用一組技能來管理學生的注意力。 您也可以在主頁上配置和更改它們。',
        workspace_domain_is_not_valid: '網域無效',
        workspace_domain_is_not_extra: '該字段是可選的。 該域必須包含小寫字母（可以包含連字符和點）。 例子：',

        stripe_connect_label: '與條紋連接',
        stripe_connect_existed_account: '您已連接 Stripe 帳戶。',
        stripe_connect_existed_text_1: '連結您的 Stripe 帳戶以開始接收課程銷售付款',
        stripe_connect_existed_text_2: 'Stripe 的設定速度很快，而且不像大多數支付處理商那樣收取任何月費，每筆交易只收取少量費用。',
        stripe_connect_existed_text_3: '如果您還沒有 Stripe 帳戶，則需要建立並維護您的 Stripe 帳戶。',
        stripe_connect_existed_text_4: '您需要處理退款和所有客戶服務問題。 我們無法控製或負責您客戶的付款。',

        //translate_to_arrange
        ai_chat_questin_text1: '学习哪种编程语言可以创建游戏？',
        ai_chat_question_text2: '前端开发者的日常任务是什么？',
        login_button: '用电子邮件登录',
        reset_password_button: '重置密码',
        email_input_text: '电子邮件',
        password_input_text: '密码',
        enter_password_warning: '请输入您的密码',
        enter_email_warning: '请输入您的电子邮件',
        embed_button: '嵌入',
        add_member_button: '添加成员',
        enter_title_warning: '请输入标题！',
        title_input_text: '标题',
        Change_title: '更改个人资料数据',
        invite_subtitle: '您的学校已准备就绪，登录并邀请您的学生',
        welcome_title_text: '欢迎来到{workspace}学校',
        access_information_start: '访问',
        vimeo_folder: 'vimeo播放器',
        sign_to_join_signup: '注册',
        payment_title_creator: '创作者计划免费试用',
        payment_title_premium: '高级计划免费试用',

        congrats: "恭喜！继续努力，实现您的目标！",
        steps: "逐步指南："
    },
};
